// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDub5_ohN1nxkMbJZqXU_vIVdrc9QXxVog',
    appId: '1:180448223018:web:4bfd6de189a47b6438c853',
    messagingSenderId: '180448223018',
    projectId: 'hospital-record-manageme-e22d1',
    authDomain: 'hospital-record-manageme-e22d1.firebaseapp.com',
    storageBucket: 'hospital-record-manageme-e22d1.firebasestorage.app',
    measurementId: 'G-ZGV17TS3RG',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDub5_ohN1nxkMbJZqXU_vIVdrc9QXxVog',
    appId: '1:180448223018:web:a482a0ae2560ce1638c853',
    messagingSenderId: '180448223018',
    projectId: 'hospital-record-manageme-e22d1',
    authDomain: 'hospital-record-manageme-e22d1.firebaseapp.com',
    storageBucket: 'hospital-record-manageme-e22d1.firebasestorage.app',
    measurementId: 'G-FMPKE8WNYN',
  );
}
